packages:
  - 'packages/*'
catalogs:
  build:
    tsdown: ^0.14.1
    unbuild: ^3.6.1
  cli:
    bumpp: ^10.2.3
    pncat: ^0.5.0
    taze: ^19.3.0
  database:
    better-sqlite3: ^12.2.0
  dev:
    typescript: ^5.9.2
  frontend:
    react: ^19.1.1
  lint:
    '@antfu/eslint-config': ^5.2.1
    eslint: ^9.34.0
    lint-staged: ^16.1.5
    simple-git-hooks: ^2.13.1
  node:
    cac: ^6.7.14
  raycast:
    '@raycast/api': ^1.102.5
    '@raycast/utils': ^2.2.1
  script:
    tsx: ^4.20.5
  test:
    vitest: ^3.2.4
  types:
    '@types/better-sqlite3': ^7.6.13
    '@types/node': ^24.3.0
    '@types/react': ^19.1.11
  utils:
    lru-cache: ^11.1.0
    tildify: ^3.0.0
onlyBuiltDependencies:
  - better-sqlite3
